### ISSUE TITLE
As a designer I need to create a sprite sheet for the player character (ant) walking +  picking up and placing down an item.

### ISSUE THREAD

**Issue by Ochamberlai2** [UoSGamesGroups/first-semester-group-19#18]
Make these as many frames as you feel it needs to look realistic

**Comment by Ochamberlai2** [comment]
Focus on the walking and then add the others if you have time

**Comment by Mpugh92** [comment]
1 hour 20 minutes to complete 
[Ant animation.zip](https://github.com/UoSGamesGroups/first-semester-group-19/files/564716/Ant.animation.zip)

**Comment by Mpugh92** [comment]
Will be completing picking up + placing down animation separate

**Comment by Ochamberlai2** [comment]
Can you please upload the file rather than commenting it, as I don't think it goes into the repository with a comment.

**Comment by Ochamberlai2** [comment]
Also I can't view psd files as I dont have photoshop on either of my pcs, so I shall have to take a look tomorrow morning before we meet with Chris
