### ISSUE TITLE
As a designer I need to do some research into some possible designs for the player character and the environment.

### ISSUE THREAD

**Issue by Ochamberlai2** [UoSGamesGroups/first-semester-group-19#2]
- Create a document showing research into different types of grass, ants and terrain for use in the game.
- This should take around 2 hours.

**Comment by Mpugh92** [comment]
[Research for ant game.zip](https://github.com/UoSGamesGroups/first-semester-group-19/files/528505/Research.for.ant.game.zip)

 Time taken to complete task : 2hours
