### ISSUE TITLE
As a designer I need to create a sprite sheet for the ant's picking up and placing down animation

### ISSUE THREAD

**Issue by Ochamberlai2** [UoSGamesGroups/first-semester-group-19#28]
this should take 4 hours

**Comment by Ochamberlai2** [comment]
Just finish whatever work you still had to do on this ( assuming it is 2 hours or less)

**Comment by Mpugh92** [comment]
Time taken to complete task 2 hours 30 minutes will be using the remaining 1 hour 30 minutes on another task
