### ISSUE TITLE
(Sam)As a programmer I need to tweak the size of the rain

### ISSUE THREAD

**Issue by Ochamberlai2** [UoSGamesGroups/first-semester-group-19#37]
Tweak the size of the rain (both particle systems and the damageRain prefab) to a place where they feel like they arent oversized or too small 

It may help to take a look at the avg size of an ant and a raindrop to get this right

this should take around 2 hours

**Comment by Sam0nline** [comment]
Just a quick clarification, do you want 'random' raindrop sizes (to certain degrees) as they are instantiated or just a consistent size relative to the player-character?

**Comment by Ochamberlai2** [comment]
I think having random sizes would be very nice, as you say only change the size to a certain degree so that they dont get too small or oversized

**Comment by Ochamberlai2** [comment]
As you have already started this, finish the last hour's worth of work

**Comment by Ochamberlai2** [comment]
This should take an hour

**Comment by Ochamberlai2** [comment]
1 hour taken
