### ISSUE TITLE
As a designer I need to Design and create the level in unity

### ISSUE THREAD

**Issue by Ochamberlai2** [UoSGamesGroups/first-semester-group-19#45]
Just create the level, put in the correct colliders if you can, if not that will only take a few minutes in the future.
This should take 4 hours

**Comment by Ochamberlai2** [comment]
Finish your level design, I am not sure how much more time you need so take around 3 hours. If you need longer than this, take time off of your other tasks as this is a critical piece of work (Please try and finish this for around monday at the latest so that I can fully complete my task for collating assets and checking all of the colliders.

**Comment by Mpugh92** [comment]
Time taken to complete task 3 hours ( can do more work after we meet on Wednesday if required ), Also i couldn't load the unity project but it wont take long to piece together the level.

**Comment by Ochamberlai2** [comment]
The task was to create the level in unity, so if possible could you take some time at uni if needs be to put your thoughts into the level in the same fashion that the existing level is created (eg floating boxes for where the grass will be) it doesn't need to include any art assets, only boxes and ignore the initial instructions from when I assigned the task, do not worry about putting in the correct colliders, I shall go through and do that myself. If you still cannot access unity then please upload an image of your level design on Monday so that I can create the level in unity. If you cannot do this then I shall have to go through and make a short level myself as this is work which absolutely must be completed by the end of this week so that we can focus on play testing in the coming week. I hope you understand why I gave a deadline of Monday for this task as this task is linked to mine, and I cannot fully complete my task without first having access to yours.

If you need further clarification please reply here, or via email.

**Comment by Ochamberlai2** [comment]
I have updated the title in case my initial explanation was too vague

**Comment by Ochamberlai2** [comment]
Task taken over as of 06/12/16
1 hour taken
