### ISSUE TITLE
As a developer I need to play test the game

### ISSUE THREAD

**Issue by Ochamberlai2** [UoSGamesGroups/first-semester-group-19#54]
Try and get 2-3 people to playtest the game and write down: What they like about it, What they dislike about it, what seemed easy, what was too hard(if anything) and what they think we should most improve upon.

Try to complete this by Monday evening so that we have the whole of Tuesday to implement any of the changes people have suggested.

I will not assign time to this task as it can vary in time taken depending on how long each person takes to playtest. The most important part of this task is to get at least 2 people playtesting each.

**Comment by Sam0nline** [comment]
I've uploaded my first edition into the **Research** folder as _Playtesting Prototype_. Let me know if there are any errors in my judgement or changes you want to suggest.

**Comment by Ochamberlai2** [comment]
Complteted for Sam 11/12/16

**Comment by Ochamberlai2** [comment]
Completed for Max 13/12/16
